CREATE TABLE `user` (
  `userID` INTEGER(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(30) COLLATE utf8mb4_general_ci NOT NULL,
  `access` INTEGER(11) NOT NULL,
  PRIMARY KEY USING BTREE (`userID`),
  UNIQUE KEY `user` USING BTREE (`user`)
) ENGINE=InnoDB
AUTO_INCREMENT=1 ROW_FORMAT=DYNAMIC CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci'
;