--------------- SQL ---------------

CREATE TABLE `weeklyshipment` (
  `shipmentID` INTEGER NOT NULL AUTO_INCREMENT,
  `shipWeek` DATE NOT NULL,
  `productID` VARCHAR(35) NOT NULL,
  `shipQty` INTEGER(0) DEFAULT NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`shipmentID`)
) ENGINE=InnoDB
CHECKSUM=0
DELAY_KEY_WRITE=0
PACK_KEYS=0
AUTO_INCREMENT=0
AVG_ROW_LENGTH=0
MIN_ROWS=0
MAX_ROWS=0
ROW_FORMAT=DEFAULT
KEY_BLOCK_SIZE=0;
ALTER TABLE `weeklyshipment`
  ADD CONSTRAINT `fk_weeklyshipment_product1` FOREIGN KEY (`productID`) REFERENCES `product` (`productID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
